source 'https://rubygems.org'

gemspec(path: Pathname(__dir__).parent.parent)

group :test do
  gem 'rake', '13.2.1'
  gem 'test-unit', '3.6.7'
  gem 'test-unit-ruby-core', '1.0'
  gem 'warning', '1.5.0'

  gem 'irb', '1.14.0'
  gem 'power_assert', '2.0.3'
end
