source 'https://rubygems.org'

gemspec(path: Pathname(__dir__).parent.parent)

group :development, :test do
  gem 'rake', '~> 13.2.1'
end

group :development do
  gem 'debug', '~> 1.9.2', require: false
  gem 'rubocop', '~> 1.63.4', require: false
  gem 'rubocop-rake', '~> 0.6.0', require: false
end

group :test do
  gem 'test-unit', '~> 3.6.2'
  gem 'warning', '~> 1.3.0'

  gem 'power_assert', '2.0.3'
  gem 'irb', '1.4.1'
end
