name: 💂➕
on:
  pull_request:
    paths:
      - '.github/workflows/dependency-review.yml'
      - 'Gemfile'

permissions:
  contents: read

jobs:
  dependency-review:
    runs-on: ubuntu-24.04
    steps:
      - name: 'Checkout Repository'
        uses: actions/checkout@v4
      - name: 'Dependency Review'
        uses: actions/dependency-review-action@v4
