name: 🤖👌🤖
on: pull_request

permissions:
  contents: write
  pull-requests: write
  # checks: read # For private repositories
  # actions: read # For private repositories

jobs:
  dependabot:
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Dependabot metadata
        id: metadata
        uses: dependabot/fetch-metadata@v2.1.0
      - name: Wait other jobs
        if: ${{ steps.metadata.outputs.update-type != 'version-update:semver-major' }}
        uses: kachick/wait-other-jobs@v3
        with:
          skip-same-workflow: 'true'
          skip-list: |
            [
              {
                "workflowFile": "ci-ruby.yml",
                "jobName": "build_and_release"
              }
            ]
        timeout-minutes: 10
      - name: Approve and merge
        if: ${{ (steps.metadata.outputs.update-type != 'version-update:semver-major') || contains(steps.metadata.outputs.dependency-names, 'DeterminateSystems') }}
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # https://github.com/kachick/anylang-template/issues/51
  selfup-runner:
    timeout-minutes: 30
    runs-on: ubuntu-24.04
    if: ${{ github.actor == 'selfup-runner[bot]' }}
    steps:
      - name: Wait other jobs
        uses: kachick/wait-other-jobs@v3
        with:
          skip-same-workflow: 'true'
        timeout-minutes: 20
      - name: Approve and merge
        run: gh pr review --approve "$PR_URL" && gh pr merge --auto --delete-branch --squash "$PR_URL"
        env:
          PR_URL: ${{ github.event.pull_request.html_url }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
